---
- name: docker conrainer start
  hosts: test_servers
  tasks:
    - name: Create a data container
      docker_container:
        name: mydata
        image: busybox
        volumes:
          - /data
...
